name = "OptiArk"
author = "ark"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6693f374c23c377bae599bedf701cc3fef04784e0beb6b59404f561835cc8059"

[versions]
fabric = "0.18.4"
minecraft = "26.1"
