name = "OptiArk"
author = "ark"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d2be2ddec937f696f51217460601813009635433d0d2e45cd2f569a20f6ed25"

[versions]
fabric = "0.19.1"
minecraft = "26.1.2"
