name = "OptiArk-Nvidium"
author = "ark"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a518076608d7e0cebea8ec841cd7ab23b497129f5b66eaeedc30bb09290bcff2"

[versions]
fabric = "0.19.1"
minecraft = "26.1.2"
