name = "OptiArk-Nvidium"
author = "ark"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e3764bc0fc150b6bd6dd236b3b54e013af8cf6d0c46730655112105a51a362a"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
