name = "OptiArk-Nvidium"
author = "ark"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f482a9d3ddd176de27191dc0964610cbedf15e48401b44f9f734639a9a3e548d"

[versions]
fabric = "0.19.1"
minecraft = "26.1.2"
