name = "OptiArk-Vulkan"
author = "ark"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc55807084edf4c15f2b4c4c1a6927dd996afce80535209f421b3756d1a2341f"

[versions]
fabric = "0.18.4"
minecraft = "26.1.1"
