name = "OptiArk-Vulkan"
author = "ark"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3135b29c323da7093b17eb125e3b143fa8a49bd170c76957b3c00f2961d760ad"

[versions]
fabric = "0.19.1"
minecraft = "26.1"
