name = "OptiArk-Vulkan"
author = "ark"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56a24a4c6d065e47a843acc93d72de735c7439ee12c29b90139199a299b9e048"

[versions]
fabric = "0.19.1"
minecraft = "26.1.2"
